[2024-12-06T17:30:46.334+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T17:30:46.360+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_dag.run_pyspark_etl manual__2024-12-06T17:30:45.125837+00:00 [queued]>
[2024-12-06T17:30:46.367+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_dag.run_pyspark_etl manual__2024-12-06T17:30:45.125837+00:00 [queued]>
[2024-12-06T17:30:46.368+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-06T17:30:46.378+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): run_pyspark_etl> on 2024-12-06 17:30:45.125837+00:00
[2024-12-06T17:30:46.381+0000] {standard_task_runner.py:72} INFO - Started process 198 to run task
[2024-12-06T17:30:46.384+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_dag', 'run_pyspark_etl', 'manual__2024-12-06T17:30:45.125837+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/scripts_etl_dags.py', '--cfg-path', '/tmp/tmpe5dfjlft']
[2024-12-06T17:30:46.388+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask run_pyspark_etl
[2024-12-06T17:30:46.410+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-06T17:30:46.456+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_dag.run_pyspark_etl manual__2024-12-06T17:30:45.125837+00:00 [running]> on host 51de1fd2edc6
[2024-12-06T17:30:46.550+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_dag' AIRFLOW_CTX_TASK_ID='run_pyspark_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T17:30:45.125837+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T17:30:45.125837+00:00'
[2024-12-06T17:30:46.552+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T17:30:46.580+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-12-06T17:30:46.581+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=2g --name arrow-spark --queue root.default /opt/***/scripts/script_etl.py
[2024-12-06T17:30:46.588+0000] {spark_submit.py:634} INFO - /usr/local/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-12-06T17:30:48.126+0000] {spark_submit.py:634} INFO - /usr/local/bin/python: can't open file '/opt/***/scripts/script_etl.py': [Errno 2] No such file or directory
[2024-12-06T17:30:48.143+0000] {spark_submit.py:634} INFO - 24/12/06 17:30:48 INFO ShutdownHookManager: Shutdown hook called
[2024-12-06T17:30:48.146+0000] {spark_submit.py:634} INFO - 24/12/06 17:30:48 INFO ShutdownHookManager: Deleting directory /tmp/spark-120da651-fc1e-456d-86fc-8db324af4f27
[2024-12-06T17:30:48.189+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=2g --name arrow-spark --queue root.default /opt/***/scripts/script_etl.py. Error code is: 2.
[2024-12-06T17:30:48.192+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=pyspark_etl_dag, task_id=run_pyspark_etl, run_id=manual__2024-12-06T17:30:45.125837+00:00, execution_date=20241206T173045, start_date=20241206T173046, end_date=20241206T173048
[2024-12-06T17:30:48.211+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T17:30:48.212+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task run_pyspark_etl (Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=2g --name arrow-spark --queue root.default /opt/***/scripts/script_etl.py. Error code is: 2.; 198)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=2g --name arrow-spark --queue root.default /opt/***/scripts/script_etl.py. Error code is: 2.
[2024-12-06T17:30:48.244+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T17:30:48.272+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T17:30:48.273+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
