[2024-12-06T18:03:00.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T18:03:00.450+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_dag.run_pyspark_etl manual__2024-12-06T18:02:59.476374+00:00 [queued]>
[2024-12-06T18:03:00.456+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_dag.run_pyspark_etl manual__2024-12-06T18:02:59.476374+00:00 [queued]>
[2024-12-06T18:03:00.457+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-06T18:03:00.467+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): run_pyspark_etl> on 2024-12-06 18:02:59.476374+00:00
[2024-12-06T18:03:00.470+0000] {standard_task_runner.py:72} INFO - Started process 198 to run task
[2024-12-06T18:03:00.474+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_dag', 'run_pyspark_etl', 'manual__2024-12-06T18:02:59.476374+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/scripts_etl_dags.py', '--cfg-path', '/tmp/tmpbke_iicr']
[2024-12-06T18:03:00.477+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask run_pyspark_etl
[2024-12-06T18:03:00.501+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-06T18:03:00.549+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_dag.run_pyspark_etl manual__2024-12-06T18:02:59.476374+00:00 [running]> on host b076fcdd6288
[2024-12-06T18:03:00.647+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_dag' AIRFLOW_CTX_TASK_ID='run_pyspark_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T18:02:59.476374+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T18:02:59.476374+00:00'
[2024-12-06T18:03:00.649+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T18:03:00.679+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-12-06T18:03:00.680+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=2g --name arrow-spark --queue root.default /opt/***/scripts/scripts_etl.py
[2024-12-06T18:03:02.340+0000] {spark_submit.py:634} INFO - File "/opt/***/scripts/scripts_etl.py", line 20
[2024-12-06T18:03:02.341+0000] {spark_submit.py:634} INFO - .getOrCreate()
[2024-12-06T18:03:02.342+0000] {spark_submit.py:634} INFO - IndentationError: unexpected indent
[2024-12-06T18:03:02.354+0000] {spark_submit.py:634} INFO - 24/12/06 18:03:02 INFO ShutdownHookManager: Shutdown hook called
[2024-12-06T18:03:02.356+0000] {spark_submit.py:634} INFO - 24/12/06 18:03:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-fe919297-aaf9-4396-9f4f-9346e099b369
[2024-12-06T18:03:02.399+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=2g --name arrow-spark --queue root.default /opt/***/scripts/scripts_etl.py. Error code is: 1.
[2024-12-06T18:03:02.403+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=pyspark_etl_dag, task_id=run_pyspark_etl, run_id=manual__2024-12-06T18:02:59.476374+00:00, execution_date=20241206T180259, start_date=20241206T180300, end_date=20241206T180302
[2024-12-06T18:03:02.424+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T18:03:02.425+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 40 for task run_pyspark_etl (Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=2g --name arrow-spark --queue root.default /opt/***/scripts/scripts_etl.py. Error code is: 1.; 198)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.executor.memory=2g --conf spark.driver.memory=2g --name arrow-spark --queue root.default /opt/***/scripts/scripts_etl.py. Error code is: 1.
[2024-12-06T18:03:02.453+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T18:03:02.475+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T18:03:02.477+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
